### ISSUE TITLE
VIPM failed to load the package

### ISSUE THREAD

**Issue by smXplorer** [kleinsimon/LV-WebView2#1]
Running VIPM free edition (2021.1), I had to use "Open Package File(s)" >> Show all Files, as the vipb file in the repo is not of the default ogp, vip or vipc type expected by VIPM.
When selecting the vipb file, I get a "VIPM could not find any package to add to the library" error message (see attached snapshot).
I am running LV 2021 SP1 64 bit.
![VIPM error](https://user-images.githubusercontent.com/10101549/200628225-c89a55b0-2f23-4b3e-a255-609dbb899307.png)

**Comment by kleinsimon** [comment]
Ah the package is not part of the repo. You can download it under Releases (https://github.com/kleinsimon/LV-WebView2/releases/tag/1.0.0.4). Choose the VIP-File.
The vipb file is the builder definition file.

**Comment by smXplorer** [comment]
Thanks. You do realize though that is not exposed to outside Github viewers?

**Comment by kleinsimon** [comment]
Do you mean that this is not clear to people not used to github? Or is the link not visible to visitors which are not logged in? I can see everything when logged out... 

I added a note to the description together with a direct link.

**Comment by smXplorer** [comment]
I am logged in and do not see any indication that something could be hidden except for the presence of 3 tags, which I have to investigate to realize they refer to releases, which I can then reveal by clicking on them. I believe your addition to the description will help noobs like myself.
