### ISSUE TITLE
Doesn't work from LV2021 32-bit

### ISSUE THREAD

**Issue by CyGaNeo** [kleinsimon/LV-WebView2#3]
Hi,

I've installed the package from VIPM on a LV 2021 32-bit.
Restarted LV and created a basic VI pointing on www.google.com

It seems that the WebView control is somehow loaded but never displays any webpage

![image](https://user-images.githubusercontent.com/86322638/233686760-3648fe37-40a7-4748-9954-6da162cfc26a.png)

If I change the basic way to use it and set the URL using a prop node, I get the following error :   
_Error 1172 occurred at Property Node in Untitled 1_
_Possible reason(s):_

_LabVIEW: (Hex 0x494) A .NET exception occurred in an external assembly. For information about correcting this error, copy the following exception (in bold), and search the Microsoft Developer Network (MSDN) Web site or the Web for a possible explanation._
_System.ArgumentException in WebView2 Control.xctl:URL Write 3.vi->WebView2_

![image](https://user-images.githubusercontent.com/86322638/233687536-e9d5cb64-16ba-49d2-a815-1e6d7607941a.png)

In the first Disable Structure, I tried to call the method Init Core (with and without overriding paths) but without success (actaully init core doesn't produce any error but URL prop node always returns the exception written upper).

**Comment by OlivierJourdan** [comment]
For the record, it works on my Lv2021 32-bit install (Windows 11) 🤔

**Comment by kleinsimon** [comment]
Hey CyGaNeo,

sorry to hear that. On what OS are you working? The error sound like there is something missing for the called DLLs
