### ISSUE TITLE
Linux and macOS are NOT supported

### ISSUE THREAD

**Issue by AntoineChalons** [kleinsimon/LV-WebView2#4]
next time you build the VIP, i suggest you untick Linux and Mac OS as supported OSes in the 'Install Requirements' tab of the package builder

![image](https://github.com/kleinsimon/LV-WebView2/assets/1894167/b19fff85-19fe-480a-a6ee-4f43e5606a5b)

**Comment by kleinsimon** [comment]
Yes, you are right... sorry for that

**Comment by kleinsimon** [comment]
closed
