### ISSUE TITLE
get HTML Source

### ISSUE THREAD

**Issue by kleinsimon** [kleinsimon/LV-WebView2#6]
From discussion on vipm.io:
`https://www.vipm.io/posts/affadd6f-f0a6-46ef-891d-55f7af74501f/`

Hi, exits a way to obtain the html source code?
Thanks

**Comment by kleinsimon** [comment]
I got this working somehow:

![image](https://github.com/kleinsimon/LV-WebView2/assets/4790227/81ad1232-3d3e-4a9d-8233-033dcb096bb9)


But the outcome is still json encoded unicode, hard to handle... I will see how to parse this

**Comment by kleinsimon** [comment]
this seems to work:

![image](https://github.com/kleinsimon/LV-WebView2/assets/4790227/0c264e7c-81d1-4db2-9d2e-a17e2990406b)

Use System.Web.Script.Serialization.JavaScriptSerializer from the "System.Web.Extension" Assembly

I will bundle this into a new event

**Comment by kleinsimon** [comment]
With the new version 1.1.0, the document source is now available via a property:

![image](https://github.com/kleinsimon/LV-WebView2/assets/4790227/a8b981e0-633e-46f8-a1dc-61bf1e5a85ff)

**Comment by abycs** [comment]
Thank Simon, i try to build (like you) for obtain directly the source code but in debug mode run perfectly, if i run normally i've got error after net object to variant. Have you got any idea for resolve it? I don't want push the navigation button and then the get source button.
![html source](https://github.com/kleinsimon/LV-WebView2/assets/65423563/16fd82da-97e6-4abc-bd42-abb11a950438)
